print("       X")
print("      XXX")
print("     XXXXX")
print("    XXXXXXX")
print("   XXXXXXXXX")
print("  XXXXXXXXXXX")
print(" XXXXXXXXXXXXX")
print("XXXXXXXXXXXXXXX")
print("      XXX")
print("      XXX")
print("      XXX")
print("     XXXXX")

print("       X        "*2)
print("      XXX       "*2)
print("     XXXXX      "*2)
print("    XXXXXXX     "*2)
print("   XXXXXXXXX    "*2)
print("  XXXXXXXXXXX   "*2)
print(" XXXXXXXXXXXXX  "*2)
print("XXXXXXXXXXXXXXX "*2)
print("      XXX       "*2)
print("      XXX       "*2)
print("      XXX       "*2)
print("     XXXXX      "*2)